allvars_bbDM = ['st_runId', 'st_lumiSection', 'st_eventId',
                'st_prefiringweight', 'st_prefiringweightup', 'st_prefiringweightdown',
                'st_scaleWeightUP', 'st_scaleWeightDOWN', 'st_pdfWeightUP', 'st_pdfWeightDOWN',
                'st_pfMetCorrPt', 'st_pfMetCorrPhi', 'st_pfMetUncJetResUp', 'st_pfMetUncJetResDown', 'st_pfMetUncJetEnUp', 'st_pfMetUncJetEnDown',
                'st_pfMetCorrSig', 'st_pfpatCaloMETPt', 'st_pfpatCaloMETPhi', 'st_pfTRKMETPt', 'st_pfTRKMETPhi',
                'WenuPhi', 'WmunuPhi', 'ZeePhi', 'ZmumuPhi',
                'ZeeRecoil', 'ZmumuRecoil', 'WenuRecoil', 'WmunuRecoil',
                'ZeeMass', 'ZmumuMass', 'Wenumass', 'Wmunumass',
                'st_isData',
                'st_THINnJet', 'st_THINjetPx', 'st_THINjetPy', 'st_THINjetPz', 'st_THINjetEnergy',
                'st_THINjetDeepCSV', 'st_THINjetHadronFlavor', 'st_THINjetNPV',
                'st_THINjetCorrUnc','st_THINPUjetIDTight',
                'st_THINjetNHadEF', 'st_THINjetCHadEF', 'st_THINjetCEmEF', 'st_THINjetNEmEF',
                'st_THINjetCMulti', 'st_THINjetNMultiplicity',
                'st_nEle', 'st_elePx', 'st_elePy', 'st_elePz', 'st_eleEnergy',
                'st_eleIsPassTight', 'st_eleIsPassLoose', 'st_eleCharge',
                'st_nPho', 'st_phoIsPassTight', 'st_phoPx', 'st_phoPy', 'st_phoPz', 'st_phoEnergy',
                'st_nMu', 'st_muPx', 'st_muPy', 'st_muPz', 'st_muEnergy', 'st_isTightMuon', 'st_muCharge',
                'st_nTau_DRBased_EleMuVeto', 'st_nTau_discBased_looseElelooseMuVeto', 'st_nTau_discBased_looseEleTightMuVeto', 'st_nTau_discBased_mediumElelooseMuVeto', 'st_nTau_discBased_TightEleTightMuVeto',
                'st_pu_nTrueInt', 'st_pu_nPUVert',
                'st_THINjetNPV',
                'mcweight', 'st_genParPt', 'st_genParSample', 'st_eletrigdecision', 'st_mutrigdecision', 'st_mettrigdecision']
